server.port=8080
spring.application.name=expense-tracker
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/expense_tracker}
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Asia/Kolkata
spring.jackson.serialization.write-dates-as-timestamps=false
